### PR TITLE
Skola24 schema support

### PR DESCRIPTION
**Pull request by nahfe**
This PR adds the ability to get schemas from the skola24 api and list all schools and classes in a domain.
The javascript and rust library is going to be open sourced soon

- [ ] Open source JS library
- [ ] Open source RS library
- [ ] Auto build JS library artifacts using my build server
- [x] Rename svg -> png for more correct name [36ec851](https://github.com/ZynerOrg/xyter/pull/471/commits/36ec85107163a324b9c90f00786d35ccab290ae1)
- [ ] Fix cache, should probably just use the RS lib for this and improve it by adding gc
- [ ] Autocorrection for schema and classes [a077bf1](https://github.com/ZynerOrg/xyter/pull/471/commits/a077bf1b20da4b4a6f1ec43b6a5e567425e618b6)
- [ ] Possibly move rasterization to JS and only produce the svg in RS
- [ ] Possibly add server/channel specific automatic domains, schools and classes using the database

May add more

### CODE REVIEW

**Comment by vermium** [comment]
Could you might move this to `/school schema`?

**Comment by nahfe** [comment]
Ok

**Comment by vermium** [comment]
You should be able to replace classes command with https://discordjs.guide/slash-commands/autocomplete.html aswell as fetching school names using https://discordjs.guide/slash-commands/autocomplete.html :) Never done it myself but should be possible

**Comment by vermium** [comment]
But that's only if you want to make it like that. Otherwise just make it like you done it right now :+1:

**Comment by nahfe** [comment]
I am thinking about doing that, just have to implement some type of cache to not have to wait seconds for the results. Could possibly use the one I made for the rust library, I just have to improve it a bit.

**Comment by vermium** [comment]
One more thing I just saw, may you change this to `/school skola24 schema` instead? Just to make space for more features in future?

**Comment by vermium** [comment]
I think it would be kinda nice if you could merge your libary into Xyters code and use TypeScript for it just to make Xyter not depending on another libary for this. I also think the package should send the result in JSON to Xyter, and then in Xyter make fancy Fields or something for the schema

**Comment by nahfe** [comment]
> I think it would be kinda nice if you could merge your libary into Xyters code and use TypeScript for it just to make Xyter not depending on another libary for this. I also think the package should send the result in JSON to Xyter, and then in Xyter make fancy Fields or something for the schema

- The RS -> JS package is not going to be included into xyter because it should be usable in more than this project and it would make a lot of extra unnecessary files, not to mention that all developers would need to be able to build rust scripts
- It it already in typescript using a .d.ts file, that file and the .js file are automatically generated by napi-rs
- I could not find a way good way to respond using json from RS and it would be more resource intensive and slow if I did, the best way was to convert a RS Vec<Vec<String> -> JS Array<Array<string>>
- If you find a better way to display the schema than by using a png, please tell me, it was the best way we found when we implemented it in the RS native bot. I could possibly generate a completely custom one

**Comment by vermium** [comment]
This closed again due to removal of branch sorry xD

**Comment by Pajsen9263** [comment]
Hello. The main goal of Xyter is to provide tools for a global market. As of now (and much likely the future too) Skola24 only operates in Sweden. The code looks good in itself but I would like to see this as a plugin (when that system is released) in the future. If Xyter provided support for mainly Swedish focused systems it would loose users as they would think the bot is made for Swedish users. I will still review it but I'm just saying that this would be better as a plugin in the future. 

Best regards Pajsen

**Review by Pajsen9263 — COMMENTED** [review]
As there are many school systems I would not rename it to School instead of Skola24.

**Comment by vermium** [comment]
> As there are many school systems I would not rename it to School instead of Skola24.

I would recommend naming it this way `/school schema schema24` This way other sources can be added by `/school schema <source>`

**Pull request closed without merging**
