### PR TITLE
Fix missing packages and make signing commits as default in VS Code

### PR DESCRIPTION
**Pull request by vermium**
Well I think the title says everything on this one.

### CODE REVIEW

**Review by Axelen123 — COMMENTED** [review]
Why are you removing the issue template here?

**Comment by vermium** [comment]
> Why are you removing the issue template here?

Because I think it didn't make any sense to users, it just confuses people since it's kinda outdated and there are not templates for the most commons stuff like Ideas and so on.

**Review by axel-06 — APPROVED** [review]
LGTM

**Comment by Axelen123** [comment]
> > Why are you removing the issue template here?
> 
> Because I think it didn't make any sense to users, it just confuses people since it's kinda outdated and there are not templates for the most commons stuff like Ideas and so on.

Ah I see

**Pull request merged**
